# excavator_cfg.py
#
# The shared ArticulationCfg. Both tasks spawn the same machine with the same
# actuators; only observations, actions and rewards differ.

from __future__ import annotations

import math
from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

from .excavator import (
    ARM_RANGE,
    JOINT_ARMS,
    JOINT_DRUMS,
    JOINT_SHROUDS,
    JOINT_WHEELS,
    CHASSIS_Z,
    ROTOR_TIP_R,
)

# Generated by the offline MJCF -> USD converter. MjcfConverter keeps only
# the output argument's directory and names the file
# "<input stem>/<input stem>.usda", so an output argument of
# <repo>/assets/excavator.usd lands at <repo>/assets/excavator/excavator.usda.
ASSETS_DIR = Path(__file__).resolve().parents[2] / "assets"
EXCAVATOR_USD_PATH = ASSETS_DIR / "excavator" / "excavator.usda"

# ---------------------------------------------------------------------------
# Prim paths
# ---------------------------------------------------------------------------
#
# The converter nests every body under Geometry/<root body>, and a child of a
# child (the drums hang off the arms) one level deeper, which the `.*`
# absorbs. scripts/run_task.py prints the real paths.
EXCAVATOR_PRIM = "{ENV_REGEX_NS}/Excavator"
CHASSIS_PRIM = EXCAVATOR_PRIM + "/Geometry/chassis"
# Coupler configs take expanded regexes, not the {ENV_REGEX_NS} placeholder.
EXCAVATOR_PRIM_REGEX = r"/World/envs/env_.*/Excavator"
# Wheels, rotors and shrouds. The shroud is what retains the load.
SOIL_CONTACT_BODIES_REGEX = (
    r"/World/envs/env_.*/Excavator/Geometry/chassis/"
    r".*(wheel_.._body|drum_(front|rear)_body|shroud_(front|rear)_body)"
)

# Wheels rest on z = 0 with the chassis origin one wheel radius up; the extra
# 2 cm keeps the solver off an initial interpenetration.
SPAWN_Z = CHASSIS_Z + 0.02

# Held during navigation, clear of the ground.
ARM_STOW_ANGLE = ARM_RANGE[0]


# ---------------------------------------------------------------------------
# Gravity
# ---------------------------------------------------------------------------
#
# Set on SimulationCfg.gravity in every env cfg.
LUNAR_GRAVITY = (0.0, 0.0, -1.62)
EARTH_G = 9.81
LUNAR_G = 1.62

# Weight scales with gravity, regolith cohesion and shear strength do not.
# The machine's 492 kg weighs 797 N here against 4824 N on Earth, so total
# tractive force at mu = 1 is ~797 N and a drum cutting a 1 m swath can exceed
# that alone. The two drums turn opposite ways so their horizontal reactions
# cancel through the frame; the drift reward term measures the cancellation.

# Wheel speed, capped below actuator capability. The machine is
# traction-limited on regolith before it is torque-limited.
MAX_WHEEL_SPEED = 5.0       # rad/s  -> 1.5 m/s at r = 0.30
MAX_YAW_SPEED = 3.0         # rad/s differential added across the two sides

# Outward acceleration at the vane tips is omega^2 * ROTOR_TIP_R, which
# reaches lunar gravity at 2.96 rad/s. The cap sits under it, at 28 rpm, where
# terrestrial bucket wheels run.
MAX_DRUM_SPEED = 2.9        # rad/s
SPIN_LIMIT = math.sqrt(LUNAR_G / ROTOR_TIP_R)


# Actuator effort ceilings. The actuator cfgs below take these, and the
# observation divides measured joint torque by them.
WHEEL_EFFORT = 120.0
ARM_EFFORT = 800.0
DRUM_EFFORT = 350.0
SHROUD_EFFORT = 200.0


def usd_status() -> str | None:
    """None if the converted asset is present and not older than its source,
    otherwise a message naming the fix."""
    source = Path(__file__).with_name("excavator.py")
    rebuild = (
        "  rebuild it (from the Isaac Lab directory):\n"
        '    isaaclab -p -c "from luna_hifi_tasks.excavator.excavator import write_mjcf;'
        ' print(write_mjcf())"\n'
        f"    rm -rf {ASSETS_DIR / 'excavator'}\n"
        f"    isaaclab -p scripts/tools/convert_mjcf.py <that path> {ASSETS_DIR / 'excavator.usd'}\n"
        "  note the output path: assets/excavator.usd, not assets/excavator/excavator.usd"
    )
    if not EXCAVATOR_USD_PATH.exists():
        return f"the excavator asset is missing:\n    {EXCAVATOR_USD_PATH}\n{rebuild}"
    if source.exists() and source.stat().st_mtime > EXCAVATOR_USD_PATH.stat().st_mtime:
        return (
            f"excavator.py is NEWER than the converted asset, so this run would use the\n"
            f"  previous geometry:\n"
            f"    {EXCAVATOR_USD_PATH}\n{rebuild}"
        )
    return None


EXCAVATOR_CFG = ArticulationCfg(
    prim_path="{ENV_REGEX_NS}/Excavator",
    spawn=sim_utils.UsdFileCfg(usd_path=str(EXCAVATOR_USD_PATH)),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, SPAWN_Z),
        # (x, y, z, w), Isaac Lab 3.x order. Identity is (0, 0, 0, 1).
        rot=(0.0, 0.0, 0.0, 1.0),
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    actuators={
        # Velocity drive, traction-sized for lunar gravity. ~123 kg per wheel
        # is ~199 N of normal force at 1.62 m/s^2, so ~60 N-m at r = 0.30
        # before slip, and the 120 ceiling is a 2x margin.
        #
        # With stiffness 0 the damping is the gain: torque is damping times
        # the velocity error. At 400 the drive reaches the effort limit at a
        # 0.3 rad/s error, so it acts as a torque source up to the ceiling at
        # any commanded speed, including the crawl a cut runs at. Tractive
        # force is bounded by effort_limit_sim and the ground.
        "wheels": ImplicitActuatorCfg(
            joint_names_expr=JOINT_WHEELS,
            effort_limit_sim=WHEEL_EFFORT,
            velocity_limit_sim=12.0,
            stiffness=0.0,
            damping=400.0,
        ),
        # Position drive, sized by dig load rather than gravity. Holding a
        # full drum out horizontally is 229 N-m at lunar gravity, and the
        # vertical component of digging resistance is larger. Raise this, not
        # the drum torque, if the arm sags or is driven up out of the cut.
        "arms": ImplicitActuatorCfg(
            joint_names_expr=JOINT_ARMS,
            effort_limit_sim=ARM_EFFORT,
            velocity_limit_sim=1.5,
            stiffness=2500.0,
            damping=250.0,
        ),
        # Velocity drive. Cutting torque is set by soil strength rather than
        # weight. Raise if a rotor stalls in soil.
        "drums": ImplicitActuatorCfg(
            joint_names_expr=JOINT_DRUMS,
            effort_limit_sim=DRUM_EFFORT,
            velocity_limit_sim=6.0,
            stiffness=0.0,
            damping=40.0,
        ),
        # Position drive. The retained load presses outward, mostly radially,
        # and what the shroud holds about the axis is the asymmetry of a
        # part-full drum, about 40 N-m at capacity. 200 is a 5x margin.
        "shrouds": ImplicitActuatorCfg(
            joint_names_expr=JOINT_SHROUDS,
            effort_limit_sim=SHROUD_EFFORT,
            velocity_limit_sim=2.0,
            stiffness=1500.0,
            damping=150.0,
        ),
    },
)
