# excavator_cfg.py
#
# The shared ArticulationCfg. Both tasks spawn the same machine with the same
# actuators; only observations, actions and rewards differ.

from __future__ import annotations

import math
from pathlib import Path

import isaaclab.sim as sim_utils
from isaaclab.actuators import ImplicitActuatorCfg
from isaaclab.assets import ArticulationCfg

from .excavator import (
    ARM_RANGE,
    JOINT_ARMS,
    JOINT_DRUMS,
    JOINT_SHROUDS,
    JOINT_WHEELS,
    CHASSIS_Z,
    ROTOR_HALF_LEN,
    ROTOR_TIP_R,
    SHROUD_OUT_R,
    SHROUD_RANGE,
)

# Generated by the offline MJCF -> USD converter; absent until it is run.
# MjcfConverter discards the output filename and keeps only its directory,
# forcing usd_file_name to "<input stem>/<input stem>.usda", so an output
# argument of <repo>/assets/excavator.usd lands the file at
# <repo>/assets/excavator/excavator.usda.
ASSETS_DIR = Path(__file__).resolve().parents[2] / "assets"
EXCAVATOR_USD_PATH = ASSETS_DIR / "excavator" / "excavator.usda"

# ---------------------------------------------------------------------------
# Prim paths
# ---------------------------------------------------------------------------
#
# The converter nests every body under Geometry/<root body>. Child bodies of
# child bodies -- the drums hang off the arms -- nest one level deeper, which
# the `.*` absorbs. scripts/run_task.py prints the real paths.
EXCAVATOR_PRIM = "{ENV_REGEX_NS}/Excavator"
CHASSIS_PRIM = EXCAVATOR_PRIM + "/Geometry/chassis"
# Coupler configs take expanded regexes, not the {ENV_REGEX_NS} placeholder.
EXCAVATOR_PRIM_REGEX = r"/World/envs/env_.*/Excavator"
# The shroud is coupled as well as the rotor: it is what actually retains the
# load, so soil that reaches it has to be stopped by it.
SOIL_CONTACT_BODIES_REGEX = (
    r"/World/envs/env_.*/Excavator/Geometry/chassis/"
    r".*(wheel_.._body|drum_(front|rear)_body|shroud_(front|rear)_body)"
)
# Every listed body brings all its geoms into the MPM coupling and the solver
# activates grid cells around each one: 31 per rotor, 15 per shroud, 7 per
# wheel. On a pad in front of the machine only the front assembly reaches soil.
FRONT_DRUM_ONLY_REGEX = (
    r"/World/envs/env_.*/Excavator/Geometry/chassis/"
    r".*(drum_front_body|shroud_front_body)"
)

# Wheels rest on z = 0 with the chassis origin one wheel radius up; the extra
# 2 cm keeps the solver off an initial interpenetration.
SPAWN_Z = CHASSIS_Z + 0.02

# Held during navigation, clear of the ground.
ARM_STOW_ANGLE = ARM_RANGE[0]

# The rotor's swept cylinder is where fill is counted, and what normalises it
# into a fraction.
BORE_RADIUS = ROTOR_TIP_R
BORE_HALF_LEN = ROTOR_HALF_LEN

# ---------------------------------------------------------------------------
# Gravity
# ---------------------------------------------------------------------------
#
# Set on SimulationCfg.gravity in every env cfg. Isaac Lab defaults to earth.
LUNAR_GRAVITY = (0.0, 0.0, -1.62)
EARTH_G = 9.81
LUNAR_G = 1.62

# Weight scales with gravity; regolith cohesion and shear strength do not. The
# machine's 492 kg weighs 797 N here against 4824 N on Earth, so traction falls
# by 6 while the force needed to cut soil is unchanged.
#
# Hence the counter-rotating drums: total tractive force is ~797 N at mu = 1,
# and a drum cutting a 1 m swath can exceed that alone. Turning the two drums
# opposite ways cancels their horizontal reactions through the frame, so
# digging costs almost no net traction. Chassis drift during a dig measures
# whether the cancellation is holding, and is part of the excavation reward.

# Wheel speed is capped below actuator capability: the machine is
# traction-limited on regolith long before it is torque-limited.
MAX_WHEEL_SPEED = 5.0       # rad/s  -> 1.5 m/s at r = 0.30
MAX_YAW_SPEED = 3.0         # rad/s differential added across the two sides

# Outward acceleration at the vane tips is omega^2 * ROTOR_TIP_R, which reaches
# lunar gravity at 2.96 rad/s. Above that regolith is thrown against the shroud
# rather than carried inward by the vanes, so the cap sits just under it. 28
# rpm, which is where terrestrial bucket wheels run.
MAX_DRUM_SPEED = 2.9        # rad/s
SPIN_LIMIT = math.sqrt(LUNAR_G / ROTOR_TIP_R)

# The shroud is position-controlled, so its action is an angle rather than a
# rate. Holding the inlet still against the ground through the arm's swing
# means commanding minus the arm angle.
SHROUD_LIMITS = SHROUD_RANGE

# Actuator effort ceilings. The actuator cfgs below take these, and the
# observation divides measured joint torque by them, so a policy input and an
# actuator limit cannot drift apart.
WHEEL_EFFORT = 120.0
ARM_EFFORT = 800.0
DRUM_EFFORT = 350.0
SHROUD_EFFORT = 200.0


def usd_status() -> str | None:
    """None if the converted asset is present and not older than its source.

    Otherwise a message naming the fix. A missing asset raises FileNotFoundError
    thirty frames inside InteractiveScene; a stale one raises nothing at all and
    silently runs the previous geometry.
    """
    source = Path(__file__).with_name("excavator.py")
    rebuild = (
        "  rebuild it (from the Isaac Lab directory):\n"
        '    isaaclab -p -c "from luna_hifi_tasks.excavator.excavator import write_mjcf;'
        ' print(write_mjcf())"\n'
        f"    rm -rf {ASSETS_DIR / 'excavator'}\n"
        f"    isaaclab -p scripts/tools/convert_mjcf.py <that path> {ASSETS_DIR / 'excavator.usd'}\n"
        "  note the output path: assets/excavator.usd, not assets/excavator/excavator.usd"
    )
    if not EXCAVATOR_USD_PATH.exists():
        return f"the excavator asset is missing:\n    {EXCAVATOR_USD_PATH}\n{rebuild}"
    if source.exists() and source.stat().st_mtime > EXCAVATOR_USD_PATH.stat().st_mtime:
        return (
            f"excavator.py is NEWER than the converted asset, so this run would use the\n"
            f"  previous drum and any geometry change would look like it did nothing:\n"
            f"    {EXCAVATOR_USD_PATH}\n{rebuild}"
        )
    return None


EXCAVATOR_CFG = ArticulationCfg(
    prim_path="{ENV_REGEX_NS}/Excavator",
    spawn=sim_utils.UsdFileCfg(usd_path=str(EXCAVATOR_USD_PATH)),
    init_state=ArticulationCfg.InitialStateCfg(
        pos=(0.0, 0.0, SPAWN_Z),
        # (x, y, z, w) -- Isaac Lab 3.x order. Identity is (0,0,0,1); under
        # xyzw, (1,0,0,0) is a 180 degree rotation about X.
        rot=(0.0, 0.0, 0.0, 1.0),
        joint_pos={".*": 0.0},
        joint_vel={".*": 0.0},
    ),
    actuators={
        # Velocity drive, traction-sized for lunar gravity. ~123 kg per wheel
        # is ~199 N of normal force at 1.62 m/s^2, so ~60 N-m at r = 0.30
        # before slip. 120 is a 2x margin. The earth-gravity figure would be
        # ~362 N-m, which the ground cannot react against.
        #
        # With stiffness 0 the damping IS the gain: torque is damping times
        # the velocity ERROR, so a slow command is a weak one. At 25 a crawl
        # command of 0.25 rad/s could raise 6.2 N-m per wheel, 83 N in total
        # against a machine that weighs 797 N here, and the wheels stalled
        # without turning. 25 was tuned so a FULL-speed command just reached
        # the effort limit, which left everything below it underpowered --
        # and a crawl is what excavation is.
        #
        # 400 reaches the effort limit at 0.3 rad/s, so the drive acts as a
        # torque source up to the ceiling at any commanded speed. What
        # actually bounds tractive force is effort_limit_sim and the ground,
        # not the gain.
        "wheels": ImplicitActuatorCfg(
            joint_names_expr=JOINT_WHEELS,
            effort_limit_sim=WHEEL_EFFORT,
            velocity_limit_sim=12.0,
            stiffness=0.0,
            damping=400.0,
        ),
        # Position drive, sized by dig load rather than gravity. Holding a full
        # drum out horizontally is 229 N-m at lunar gravity; resisting the
        # vertical component of digging resistance is larger and does not
        # shrink with gravity. Raise this, not the drum torque, if the arm sags
        # or is driven up out of the cut.
        "arms": ImplicitActuatorCfg(
            joint_names_expr=JOINT_ARMS,
            effort_limit_sim=ARM_EFFORT,
            velocity_limit_sim=1.5,
            stiffness=2500.0,
            damping=250.0,
        ),
        # Velocity drive. Cutting torque is set by soil strength, not weight.
        # Raise if a rotor stalls in soil; it costs no traction, which is what
        # the counter-rotating pair buys.
        "drums": ImplicitActuatorCfg(
            joint_names_expr=JOINT_DRUMS,
            effort_limit_sim=DRUM_EFFORT,
            velocity_limit_sim=6.0,
            stiffness=0.0,
            damping=40.0,
        ),
        # Position drive. The shroud carries the retained load pressing
        # outward, which is mostly radial and so produces little torque about
        # the axis; what it does have to hold is the asymmetry of a part-full
        # drum, about 40 N-m at capacity. 200 is a 5x margin.
        "shrouds": ImplicitActuatorCfg(
            joint_names_expr=JOINT_SHROUDS,
            effort_limit_sim=SHROUD_EFFORT,
            velocity_limit_sim=2.0,
            stiffness=1500.0,
            damping=150.0,
        ),
    },
)
